### ISSUE TITLE
支不支持使用背景selector？

### ISSUE THREAD

**Issue by qiushui95** [chinnsenn/SubmitButton#1]
项目里面的登陆按钮是否启用会根据输入状态变化，按钮颜色肯定也得变化

**Comment by chinnsenn** [comment]
做的时候确实只考虑到实现动画实现的效果，没有过多考虑实际使用场景，你的两个意见我都看到了，我有空会改进一下。

**Comment by qiushui95** [comment]
> 做的时候确实只考虑到实现动画实现的效果，没有过多考虑实际使用场景，你的两个意见我都看到了，我有空会改进一下。

最近在新写项目，比较忙，不然我也可以PR
